; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for Bad Apple:

.export _music_data_bad_apple:=music_data_bad_apple

music_data_bad_apple:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : Song 1
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_bad_apple
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env4,@env3,@env6,@env0 ; 00 : Square1
	.word @env1,@env3,@env6,@env0 ; 01 : Square2
	.word @env2,@env3,@env6,@env0 ; 02 : Triangle
	.word @env5,@env3,@env6,@env0 ; 03 : Noise

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$c5,$7f,$00,$02
@env2:
	.byte $00,$cf,$7f,$00,$02
@env3:
	.byte $c0,$7f,$00,$01
@env4:
	.byte $00,$c4,$7f,$00,$02
@env5:
	.byte $00,$c7,$7f,$00,$02
@env6:
	.byte $7f,$00,$00

@samples:
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$e1,$0f,$40 ; 00 chunk000 (Pitch:15)
	.byte $79+.lobyte(FAMISTUDIO_DPCM_PTR),$e1,$0f,$40 ; 01 chunk001 (Pitch:15)
	.byte $b2+.lobyte(FAMISTUDIO_DPCM_PTR),$e1,$0f,$40 ; 02 chunk002 (Pitch:15)
	.byte $eb+.lobyte(FAMISTUDIO_DPCM_PTR),$e1,$0f,$40 ; 03 chunk003 (Pitch:15)
	.byte $124+.lobyte(FAMISTUDIO_DPCM_PTR),$e1,$0f,$40 ; 04 chunk004 (Pitch:15)
	.byte $15d+.lobyte(FAMISTUDIO_DPCM_PTR),$e1,$0f,$40 ; 05 chunk005 (Pitch:15)
	.byte $196+.lobyte(FAMISTUDIO_DPCM_PTR),$e1,$0f,$40 ; 06 chunk006 (Pitch:15)
	.byte $1cf+.lobyte(FAMISTUDIO_DPCM_PTR),$e1,$0f,$40 ; 07 chunk007 (Pitch:15)
	.byte $208+.lobyte(FAMISTUDIO_DPCM_PTR),$e1,$0f,$40 ; 08 chunk008 (Pitch:15)
	.byte $241+.lobyte(FAMISTUDIO_DPCM_PTR),$e1,$0f,$40 ; 09 chunk009 (Pitch:15)
	.byte $27a+.lobyte(FAMISTUDIO_DPCM_PTR),$e1,$0f,$40 ; 0a chunk010 (Pitch:15)
	.byte $2b3+.lobyte(FAMISTUDIO_DPCM_PTR),$e1,$0f,$40 ; 0b chunk011 (Pitch:15)
	.byte $2ec+.lobyte(FAMISTUDIO_DPCM_PTR),$e1,$0f,$40 ; 0c chunk012 (Pitch:15)
	.byte $325+.lobyte(FAMISTUDIO_DPCM_PTR),$e1,$0f,$40 ; 0d chunk013 (Pitch:15)
	.byte $35e+.lobyte(FAMISTUDIO_DPCM_PTR),$e1,$0f,$40 ; 0e chunk014 (Pitch:15)
	.byte $397+.lobyte(FAMISTUDIO_DPCM_PTR),$e1,$0f,$40 ; 0f chunk015 (Pitch:15)
	.byte $3d0+.lobyte(FAMISTUDIO_DPCM_PTR),$e1,$0f,$40 ; 10 chunk016 (Pitch:15)
	.byte $409+.lobyte(FAMISTUDIO_DPCM_PTR),$e1,$0f,$40 ; 11 chunk017 (Pitch:15)
	.byte $442+.lobyte(FAMISTUDIO_DPCM_PTR),$e1,$0f,$40 ; 12 chunk018 (Pitch:15)
	.byte $47b+.lobyte(FAMISTUDIO_DPCM_PTR),$e1,$0f,$40 ; 13 chunk019 (Pitch:15)
	.byte $4b4+.lobyte(FAMISTUDIO_DPCM_PTR),$e1,$0f,$40 ; 14 chunk020 (Pitch:15)
	.byte $4ed+.lobyte(FAMISTUDIO_DPCM_PTR),$e1,$0f,$40 ; 15 chunk021 (Pitch:15)
	.byte $526+.lobyte(FAMISTUDIO_DPCM_PTR),$e1,$0f,$40 ; 16 chunk022 (Pitch:15)
	.byte $55f+.lobyte(FAMISTUDIO_DPCM_PTR),$e1,$0f,$40 ; 17 chunk023 (Pitch:15)
	.byte $598+.lobyte(FAMISTUDIO_DPCM_PTR),$e1,$0f,$40 ; 18 chunk024 (Pitch:15)
	.byte $5d1+.lobyte(FAMISTUDIO_DPCM_PTR),$e1,$0f,$40 ; 19 chunk025 (Pitch:15)
	.byte $60a+.lobyte(FAMISTUDIO_DPCM_PTR),$e1,$0f,$40 ; 1a chunk026 (Pitch:15)
	.byte $643+.lobyte(FAMISTUDIO_DPCM_PTR),$e1,$0f,$40 ; 1b chunk027 (Pitch:15)
	.byte $67c+.lobyte(FAMISTUDIO_DPCM_PTR),$e1,$0f,$40 ; 1c chunk028 (Pitch:15)
	.byte $6b5+.lobyte(FAMISTUDIO_DPCM_PTR),$e1,$0f,$40 ; 1d chunk029 (Pitch:15)
	.byte $6ee+.lobyte(FAMISTUDIO_DPCM_PTR),$e1,$0f,$40 ; 1e chunk030 (Pitch:15)
	.byte $727+.lobyte(FAMISTUDIO_DPCM_PTR),$e1,$0f,$40 ; 1f chunk031 (Pitch:15)
	.byte $760+.lobyte(FAMISTUDIO_DPCM_PTR),$e1,$0f,$40 ; 20 chunk032 (Pitch:15)
	.byte $799+.lobyte(FAMISTUDIO_DPCM_PTR),$e1,$0f,$40 ; 21 chunk033 (Pitch:15)
	.byte $7d2+.lobyte(FAMISTUDIO_DPCM_PTR),$e1,$0f,$40 ; 22 chunk034 (Pitch:15)
	.byte $80b+.lobyte(FAMISTUDIO_DPCM_PTR),$e1,$0f,$40 ; 23 chunk035 (Pitch:15)
	.byte $844+.lobyte(FAMISTUDIO_DPCM_PTR),$e1,$0f,$40 ; 24 chunk036 (Pitch:15)
	.byte $87d+.lobyte(FAMISTUDIO_DPCM_PTR),$e1,$0f,$40 ; 25 chunk037 (Pitch:15)
	.byte $8b6+.lobyte(FAMISTUDIO_DPCM_PTR),$e1,$0f,$40 ; 26 chunk038 (Pitch:15)
	.byte $8ef+.lobyte(FAMISTUDIO_DPCM_PTR),$e1,$0f,$40 ; 27 chunk039 (Pitch:15)
	.byte $928+.lobyte(FAMISTUDIO_DPCM_PTR),$e1,$0f,$40 ; 28 chunk040 (Pitch:15)
	.byte $961+.lobyte(FAMISTUDIO_DPCM_PTR),$e1,$0f,$40 ; 29 chunk041 (Pitch:15)
	.byte $99a+.lobyte(FAMISTUDIO_DPCM_PTR),$e1,$0f,$40 ; 2a chunk042 (Pitch:15)
	.byte $9d3+.lobyte(FAMISTUDIO_DPCM_PTR),$e1,$0f,$40 ; 2b chunk043 (Pitch:15)
	.byte $a0c+.lobyte(FAMISTUDIO_DPCM_PTR),$e1,$0f,$40 ; 2c chunk044 (Pitch:15)
	.byte $a45+.lobyte(FAMISTUDIO_DPCM_PTR),$e1,$0f,$40 ; 2d chunk045 (Pitch:15)
	.byte $a7e+.lobyte(FAMISTUDIO_DPCM_PTR),$e1,$0f,$40 ; 2e chunk046 (Pitch:15)
	.byte $ab7+.lobyte(FAMISTUDIO_DPCM_PTR),$e1,$0f,$40 ; 2f chunk047 (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40 ; 30 cymbalriser331 (Pitch:15)

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ref1:
	.byte $ff, $cf, $48, $ff, $cf, $48, $ff, $cf, $48, $ff, $cf, $48, $ff, $cf, $48, $ff, $cf, $48, $ff, $cf, $48
	.byte $41, $0e
	.word @song0ref1
	.byte $48, $ff, $cf, $48, $ff, $cf
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid)
	.byte $41, $0e
	.word @song0ref1
	.byte $48, $ff, $cf, $48, $80, $04, $ff, $cd, $48
	.byte $41, $0e
	.word @song0ref1
	.byte $48, $00, $ff, $cd, $48
	.byte $41, $0e
	.word @song0ref1
@song0ref58:
	.byte $48, $28, $97, $2a, $97, $2b, $97, $2d, $97, $2f, $97, $00, $97, $34, $97, $32, $97, $48, $2f, $b1, $28, $b1, $2f, $97
	.byte $2d, $97, $2b, $97, $2a, $97, $48, $28, $97, $2a, $97, $2b, $97, $2d, $97, $2f, $97, $00, $97, $2d, $97, $2b, $97, $48
	.byte $2a, $b1, $2b, $b1, $2d, $b1, $2f, $b1
	.byte $41, $34
	.word @song0ref58
	.byte $48, $04, $ff, $cd, $48
	.byte $41, $0e
	.word @song0ref1
	.byte $42
	.word @song0ch0loop
@song0ch1:
@song0ref128:
	.byte $ff, $cf, $ff, $cf, $ff, $cf, $ff, $cf, $ff, $cf, $ff, $cf, $ff, $cf
	.byte $41, $0e
	.word @song0ref128
	.byte $ff, $cf, $ff, $cf
@song0ch1loop:
	.byte $82
@song0ref151:
	.byte $10, $a5, $1c, $91, $00, $83, $1c, $89, $1a, $8b, $1c
@song0ref162:
	.byte $89, $10, $a5, $1c, $91, $00, $83, $1c, $89, $1a, $8b, $1c, $89
@song0ref175:
	.byte $10, $a5, $1c, $91, $00, $83, $1c, $89, $1a, $8b, $1c, $89, $1a, $8b, $1c, $89, $1f, $8b, $21, $89, $23, $85, $21, $83
	.byte $1f, $83, $1c, $83, $21, $85, $1f, $83, $1c, $83, $1a, $83, $13, $a5, $1c, $91, $00, $83, $1c, $89, $1a, $8b, $1c, $89
	.byte $13, $a5, $1c, $91, $00, $83, $1c, $89, $1a, $8b, $1c, $89, $15, $a5, $21, $91, $00, $83, $1f, $89, $1c, $8b, $1a, $89
	.byte $1f, $8b, $1c, $89, $00, $8b, $1a, $89, $17, $8b, $00, $89, $15, $8b, $13
	.byte $41, $19
	.word @song0ref162
	.byte $41, $3e
	.word @song0ref175
@song0ref268:
	.byte $1c, $91, $00, $83, $1c, $89, $1a, $8b, $1c, $89, $1f, $8b, $21, $89, $23, $8b, $26, $89, $23, $85, $26, $83, $28, $83
	.byte $2b, $83, $28, $85, $2b, $83, $2d, $83, $32, $83, $34, $ff, $cd, $ff, $cf, $00, $ff, $cd, $ff, $cf, $ff, $cf, $ff, $cf
	.byte $ff, $cf, $ff, $cf
	.byte $41, $6f
	.word @song0ref151
	.byte $41, $19
	.word @song0ref162
	.byte $41, $3e
	.word @song0ref175
	.byte $41, $22
	.word @song0ref268
	.byte $41, $6f
	.word @song0ref151
	.byte $41, $19
	.word @song0ref162
	.byte $41, $3e
	.word @song0ref175
	.byte $41, $22
	.word @song0ref268
	.byte $00, $ff, $cd
	.byte $41, $0e
	.word @song0ref128
	.byte $42
	.word @song0ch1loop
@song0ch2:
	.byte $41, $0e
	.word @song0ref128
	.byte $ff, $cf, $84
@song0ref359:
	.byte $10
@song0ref360:
	.byte $a5, $1c, $93, $00, $81, $1c, $89, $1a
@song0ref368:
	.byte $8b, $1c
@song0ref370:
	.byte $89, $10, $a5, $1c, $93, $00, $81, $1c, $89, $1a, $8b, $1c, $89
@song0ref383:
	.byte $10, $a5, $1c, $93, $00, $81, $1c, $89, $1a, $8b, $1c, $89, $13, $97, $10, $8b, $0b, $89, $15, $97, $1f
	.byte $41, $1b
	.word @song0ref368
@song0ref407:
	.byte $10, $a5, $1c, $93, $00, $81, $1c, $89, $1a, $8b, $1c, $89, $15, $97, $13, $8b, $10, $89, $13, $97, $15
	.byte $41, $1b
	.word @song0ref368
	.byte $41, $15
	.word @song0ref383
	.byte $41, $1b
	.word @song0ref368
	.byte $41, $15
	.word @song0ref407
	.byte $8b, $1c, $89
@song0ch2loop:
	.byte $41, $2d
	.word @song0ref359
@song0ref447:
	.byte $8b, $1c, $89, $13, $a5, $1f, $93, $00, $81, $1f, $89, $1d, $8b, $1f, $89, $13, $a5, $1f, $93, $00, $81, $1f, $89, $1d
	.byte $8b, $1f, $89, $15, $a5, $1f, $93, $00, $81, $1f, $89, $1d, $8b, $1f, $89, $18, $97, $16, $8b, $13, $89, $16, $97, $18
	.byte $8b, $1f
	.byte $41, $19
	.word @song0ref370
	.byte $41, $15
	.word @song0ref383
@song0ref503:
	.byte $8b, $1c, $89, $13, $a5, $1c, $93, $00, $81, $1f, $89, $21, $8b, $23, $89, $13, $a5, $1f, $93, $00, $81, $21, $89, $23
	.byte $8b, $26, $89, $15, $a5, $1c, $93, $00, $81, $1c, $89, $1a, $8b, $1c, $89, $1a, $97, $17, $8b, $13, $89, $17, $97, $1a
	.byte $8b, $1f, $89, $10, $ff, $cd
	.byte $41, $0e
	.word @song0ref128
	.byte $41, $2d
	.word @song0ref359
	.byte $41, $32
	.word @song0ref447
	.byte $41, $19
	.word @song0ref370
	.byte $41, $15
	.word @song0ref383
	.byte $41, $34
	.word @song0ref503
	.byte $41, $2c
	.word @song0ref360
	.byte $41, $32
	.word @song0ref447
	.byte $41, $19
	.word @song0ref370
	.byte $41, $15
	.word @song0ref383
	.byte $41, $34
	.word @song0ref503
	.byte $41, $2c
	.word @song0ref360
	.byte $41, $32
	.word @song0ref447
	.byte $41, $19
	.word @song0ref370
	.byte $41, $15
	.word @song0ref383
	.byte $41, $33
	.word @song0ref503
	.byte $42
	.word @song0ch2loop
@song0ch3:
	.byte $86
@song0ref609:
	.byte $37, $8b, $00, $a3, $37, $8b, $00, $a3, $37, $8b, $00, $a3, $37, $00, $89, $37, $00, $87, $37, $00, $89, $37, $00, $87
	.byte $41, $0e
	.word @song0ref609
	.byte $95, $37, $00, $95
	.byte $41, $18
	.word @song0ref609
	.byte $37, $8b, $00, $a3, $37, $8b, $00, $a3, $37, $8b, $00, $97, $34, $89, $38, $00, $95, $38, $00, $95
@song0ref663:
	.byte $37, $8b, $00, $89, $34, $89, $00, $8b, $37, $8b, $00, $89, $34, $8b, $00, $89, $37, $8b, $00, $89, $34, $8b, $00, $89
	.byte $37, $85, $00, $83, $37, $83, $00, $83, $37, $85, $00, $83, $37, $83, $00, $83
	.byte $41, $1b
	.word @song0ref663
	.byte $8f, $37, $85, $00, $8f
	.byte $41, $28
	.word @song0ref663
	.byte $41, $13
	.word @song0ref663
	.byte $d7
	.byte $41, $28
	.word @song0ref663
	.byte $41, $1b
	.word @song0ref663
	.byte $8f, $37, $85, $00, $8f
	.byte $41, $28
	.word @song0ref663
	.byte $41, $13
	.word @song0ref663
	.byte $97, $34, $89, $37, $8b, $00, $89, $37, $8b, $00, $89
	.byte $41, $28
	.word @song0ref663
	.byte $41, $1b
	.word @song0ref663
	.byte $8f, $37, $85, $00, $8f
	.byte $41, $28
	.word @song0ref663
	.byte $41, $10
	.word @song0ref663
	.byte $38, $8f, $39, $8f, $3a, $8d, $3b, $8f, $3c, $8f, $3d, $8d
@song0ch3loop:
	.byte $41, $28
	.word @song0ref663
	.byte $41, $1b
	.word @song0ref663
	.byte $8f, $37, $85, $00, $8f
	.byte $41, $28
	.word @song0ref663
	.byte $41, $13
	.word @song0ref663
	.byte $97, $34, $89, $37, $8b, $00, $89, $37, $8b, $00, $89
	.byte $41, $28
	.word @song0ref663
	.byte $41, $1b
	.word @song0ref663
	.byte $8f, $37, $85, $00, $8f
	.byte $41, $28
	.word @song0ref663
	.byte $41, $10
	.word @song0ref663
@song0ref821:
	.byte $38, $8f, $39, $8f, $3a, $8d, $3b, $8f, $3c, $8f, $3d, $8d
@song0ref833:
	.byte $34, $b1, $00, $b1, $2b, $b1, $00, $b1, $99, $34, $97, $00, $97, $3d, $97, $25, $b1, $00, $b1, $99, $36, $97, $38, $97
	.byte $00, $97, $2b, $b1, $00, $b1, $b3, $38, $97, $00, $97, $25, $b1, $00, $b1
	.byte $41, $23
	.word @song0ref833
	.byte $38, $8f, $39, $8f, $3a, $8d, $3b, $8f, $3c, $8f, $3d, $8d
	.byte $41, $28
	.word @song0ref663
	.byte $41, $1b
	.word @song0ref663
	.byte $8f, $37, $85, $00, $8f
	.byte $41, $28
	.word @song0ref663
	.byte $41, $13
	.word @song0ref663
	.byte $97, $34, $89, $37, $8b, $00, $89, $37, $8b, $00, $89
	.byte $41, $28
	.word @song0ref663
	.byte $41, $1b
	.word @song0ref663
	.byte $8f, $37, $85, $00, $8f
	.byte $41, $28
	.word @song0ref663
	.byte $41, $10
	.word @song0ref663
	.byte $38, $8f, $39, $8f, $3a, $8d, $3b, $8f, $3c, $8f, $3d, $8d
	.byte $41, $28
	.word @song0ref663
	.byte $41, $1b
	.word @song0ref663
	.byte $8f, $37, $85, $00, $8f
	.byte $41, $28
	.word @song0ref663
	.byte $41, $13
	.word @song0ref663
	.byte $97, $34, $89, $37, $8b, $00, $89, $37, $8b, $00, $89
	.byte $41, $28
	.word @song0ref663
	.byte $41, $1b
	.word @song0ref663
	.byte $8f, $37, $85, $00, $8f
	.byte $41, $28
	.word @song0ref663
	.byte $41, $10
	.word @song0ref663
	.byte $41, $33
	.word @song0ref821
	.byte $41, $23
	.word @song0ref833
	.byte $38, $8f, $39, $8f, $3a, $8d, $3b, $8f, $3c, $8f, $3d, $8d, $42
	.word @song0ch3loop
@song0ch4:
	.byte $41, $0e
	.word @song0ref128
	.byte $31, $ff, $99, $00, $b1
	.byte $41, $0e
	.word @song0ref128
	.byte $ff, $cf
@song0ch4loop:
	.byte $41, $0e
	.word @song0ref128
	.byte $41, $0e
	.word @song0ref128
	.byte $ff, $cf, $ff, $cf, $01, $e5, $02, $e5, $03, $e5, $04, $e5, $05, $e5, $06, $e5, $07, $e5, $08, $e5, $09, $e5, $0a, $e5
	.byte $0b, $e5, $0c, $e5, $0d, $e5, $0e, $e5, $0f, $e5, $10, $e5, $11, $e5, $12, $e5, $13, $e5, $14, $e5, $15, $e5, $16, $e5
	.byte $17, $e5, $18, $e5, $19, $e5, $1a, $e5, $1b, $e5, $1c, $e5, $1d, $e5, $1e, $e5, $1f, $e5, $20, $e5, $21, $e5, $22, $e5
	.byte $23, $e5, $24, $e5, $25, $e5, $26, $e5, $27, $e5, $28, $e5, $29, $e5, $2a, $e5, $2b, $e5, $2c, $e5, $2d, $e5, $2e, $e5
	.byte $2f, $e5, $30, $b1, $00, $b1, $42
	.word @song0ch4loop
