import sys

with open(sys.argv[1], 'rb') as input_file:
    with open(sys.argv[2], 'w') as output_file:
        _ = output_file.write(
""" /// Do not modify. autogenerated by `generate_rom_header.py`
#ifndef ROM_H
#define ROM_H

#include <stdint.h>

/**
* array of the prg-rom of an NROM cartrige using CHR-RAM
*/
const uint8_t rom_arr[] = { """)
        _ = input_file.read(16)
        while True:
            byte = input_file.read(1)
            if not byte:
                break
            _ = output_file.write(f"  0x{byte[0]:02X},\n")
        _ = output_file.write(
""" };

#endif
        """)
